# Generated by Django 3.2.7 on 2021-10-02 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('CarID', models.AutoField(primary_key=True, serialize=False)),
                ('CarName', models.CharField(blank=True, max_length=500, null=True, verbose_name='Car Name')),
                ('CarImage', models.ImageField(upload_to='productimg', verbose_name='Vehicle Image')),
                ('RefNo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ref No')),
                ('ChassisNo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chassis No')),
                ('ModelCode', models.CharField(blank=True, max_length=500, null=True, verbose_name='Model Code')),
                ('EngineSize', models.CharField(blank=True, max_length=500, null=True, verbose_name='Engine Size')),
                ('Location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Location')),
                ('Version', models.CharField(blank=True, max_length=500, null=True, verbose_name='Version/Class')),
                ('Drive', models.CharField(blank=True, max_length=500, null=True, verbose_name='Drive')),
                ('Transmission', models.CharField(blank=True, max_length=500, null=True, verbose_name='Transmission')),
                ('Mileage', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mileage')),
                ('EngineCode', models.CharField(blank=True, max_length=500, null=True, verbose_name='Engine Code')),
                ('ExtColor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ext Color')),
                ('Fuel', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuel')),
                ('Seats', models.CharField(blank=True, max_length=500, null=True, verbose_name='Seats')),
                ('Door', models.CharField(blank=True, max_length=500, null=True, verbose_name='Door')),
                ('M3', models.CharField(blank=True, max_length=500, null=True, verbose_name='M3')),
                ('Dimensions', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dimensions')),
                ('Weight', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vehicle Weight')),
                ('MaxCap', models.CharField(blank=True, max_length=500, null=True, verbose_name='Max Capicity')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('Price', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vehicle Price')),
                ('TotalPrice', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total Price')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=500, verbose_name='Vehicle Type')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=500, verbose_name='Company Name')),
                ('CompanyStock', models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Stock')),
                ('CompanyLogo', models.ImageField(upload_to='productimg', verbose_name='Company Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=100, verbose_name='Country Name')),
                ('flagImage', models.ImageField(upload_to='productimg', verbose_name='Flag Image')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('locality', models.CharField(max_length=200, verbose_name='Locality')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zipcode', models.IntegerField(verbose_name='Zip Code')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country', verbose_name='Country Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('DiscountID', models.AutoField(primary_key=True, serialize=False)),
                ('Discount', models.CharField(blank=True, default='Add discount like (30% Off or more)', max_length=100, null=True, verbose_name='Discount')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingYM',
            fields=[
                ('ManufacturingYMID', models.AutoField(primary_key=True, serialize=False)),
                ('ManufacturingDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCategorie',
            fields=[
                ('OtherCategorieID', models.AutoField(primary_key=True, serialize=False)),
                ('OtherCategoryName', models.CharField(blank=True, default='add othere category like (LHD, Hybrid, electric)', max_length=200, null=True, verbose_name='Other Category Name')),
                ('CatImage', models.ImageField(upload_to='productimg', verbose_name='Other Category Image')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('PriceID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.CharField(blank=True, default='add price range like ($500 - $1,000)', max_length=100, null=True, verbose_name='Price Range')),
            ],
        ),
        migrations.CreateModel(
            name='Steering',
            fields=[
                ('SteeringID', models.AutoField(primary_key=True, serialize=False)),
                ('SteeringName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Steering Name')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.company', verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.country', verbose_name='CountryName'),
        ),
        migrations.AddField(
            model_name='car',
            name='discount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.discount', verbose_name='By Discount'),
        ),
        migrations.AddField(
            model_name='car',
            name='mfdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.manufacturingym', verbose_name='Manufacturing Date'),
        ),
        migrations.AddField(
            model_name='car',
            name='othercategorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.othercategorie', verbose_name='Other Categories'),
        ),
        migrations.AddField(
            model_name='car',
            name='pricerange',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.pricerange', verbose_name='Price Range'),
        ),
        migrations.AddField(
            model_name='car',
            name='steering',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.steering', verbose_name='Steering'),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cartype', verbose_name='Vehicle Type'),
        ),
    ]
