# Generated by Django 3.2.7 on 2021-10-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('CurrecnyID', models.AutoField(primary_key=True, serialize=False)),
                ('CurrencyName', models.CharField(default='USD', max_length=50, verbose_name='Currency Name')),
            ],
        ),
    ]
