# Generated by Django 3.2.7 on 2021-10-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('LanguageID', models.AutoField(primary_key=True, serialize=False)),
                ('LanguageName', models.CharField(default='add language like English', max_length=50, verbose_name='Language Name')),
            ],
        ),
        migrations.AlterField(
            model_name='currencies',
            name='CurrencyName',
            field=models.CharField(default='add currency like USD', max_length=50, verbose_name='Currency Name'),
        ),
    ]
