# Generated by Django 3.2.7 on 2021-10-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_languages_fimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHeading',
            fields=[
                ('MainHeadingID', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=50, verbose_name='Website Purpose')),
                ('stock', models.CharField(max_length=100, verbose_name='Total Stock')),
                ('todaystock', models.CharField(max_length=50, verbose_name='Today Stock')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.country', verbose_name='Country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.currencies', verbose_name='Currency')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.languages', verbose_name='Language')),
            ],
        ),
    ]
