# Generated by Django 3.2.7 on 2021-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mainheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSituation',
            fields=[
                ('ShippingSituationID', models.AutoField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200, verbose_name='Heading')),
                ('Date', models.DateTimeField(verbose_name='Date')),
                ('Description', models.TextField()),
            ],
        ),
    ]
