# Generated by Django 3.2.7 on 2021-10-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_salesoffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewHeading', models.CharField(max_length=50, verbose_name='Review Heading')),
                ('UserName', models.CharField(max_length=100, verbose_name='User Name')),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='productimg', verbose_name='Review Image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.car', verbose_name='Vehicle Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.company', verbose_name='Vehicle Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.country', verbose_name='Country Name')),
            ],
        ),
    ]
