# Generated by Django 3.2.7 on 2021-10-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('QAID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=200, verbose_name='Question')),
                ('Answer', models.TextField(verbose_name='Answer')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='CarName',
            field=models.CharField(blank=True, default='Car Name like Honda City (IDSI)', max_length=500, null=True, verbose_name='Car Name'),
        ),
    ]
