# Generated by Django 3.2.7 on 2023-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20, verbose_name='User Name')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact No')),
            ],
        ),
    ]
